version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:

      # Install Python packages
      - pip install --requirement requirements.txt

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase.."
  build:
    commands:
      - python src/Perfiles.py
      - python src/Posts.py
  post_build:
    commands:
      - echo "We are in the postbuild block"
artifacts:
  files:
    - '**/*'
